const predefinedCrosses3 = [
  // BARRED CHOCOLATE CROSSES, not done

{ sire: 'Barred Chocolate', dam: 'Auburn', results: { male: ['Barred Chocolate', 'Auburn'], maleGenotype: ['Bb ee', 'bb ee'], maleRatio: [1, 1], female: ['Barred Chocolate', 'Auburn'], femaleGenotype: ['Bb e-', 'bb e-'], femaleRatio: [1, 1] } },

{ sire: 'Barred Chocolate', dam: 'Barred Black', results: { male: ['Black', 'Barred Black', 'Bronze'], maleGenotype: ['BB Ee', 'Bb Ee', 'bb Ee'], maleRatio: [1, 2, 1], female: ['Chocolate', 'Barred Chocolate', 'Auburn'], femaleGenotype: ['BB e-', 'Bb e-', 'bb e-'], femaleRatio: [1, 2, 1] } },

{ sire: 'Barred Chocolate', dam: 'Barred Chocolate', results: { male: ['Chocolate', 'Barred Chocolate', 'Auburn'], maleGenotype: ['BB ee', 'Bb ee', 'bb ee'], maleRatio: [1, 2, 1], female: ['Chocolate', 'Barred Chocolate', 'Auburn'], femaleGenotype: ['BB e-', 'Bb e-', 'bb e-'], femaleRatio: [1, 2, 1] } },


{ sire: 'Barred Chocolate', dam: 'Barred Slate', results: { male: ['Slate', 'Black', 'Barred Slate', 'Barred Black', 'Red Slate', 'Bronze'], maleGenotype: ['BB Dd Ee', 'BB Ee', 'Bb Dd Ee', 'Bb Ee', 'bb Dd Ee', 'bb Ee'], maleRatio: [1, 1, 2, 2, 1, 1], female: ['Chocolate Slate', 'Chocolate', 'Barred Chocolate Slate', 'Barred Chocolate', 'Chocolate Red Slate', 'Auburn'], femaleGenotype: ['BB Dd e-', 'BB e-', 'Bb Dd e-', 'Bb e-', 'bb Dd e-', 'bb e-'], femaleRatio: [1, 1, 2, 2, 1, 1] } },

{ sire: 'Barred Chocolate', dam: 'Black', results: { male: ['Black', 'Barred Black'], maleGenotype: ['BB Ee', 'Bb Ee'], maleRatio: [1, 1], female: ['Chocolate', 'Barred Chocolate'], femaleGenotype: ['BB e-', 'Bb e-'], femaleRatio: [1, 1] } },

{ sire: 'Barred Chocolate', dam: 'Black Winged Bronze', results: { male: ['Barred Black', 'Bronze.'], maleGenotype: ['Bb1 Ee', 'bb1 Ee'], maleRatio: [1, 1], female: ['Barred Chocolate', 'Auburn'], femaleGenotype: ['Bb1 e-', 'bb1 e-'], femaleRatio: [1, 1] } },

{ sire: 'Barred Chocolate', dam: 'Blue Calico', results: { male: ['Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black', 'Red Slate', 'Blue Red Bronze.', 'Bronze-', 'Red Bronze.'], maleGenotype: ['Bb1 Ccg Dd Ee Nn', 'Bb1 Ccg Dd Ee Nn Rr', 'Bb1 Ccg Ee Nn', 'Bb1 Ccg Ee Nn Rr', 'bb1 Ccg Dd Ee Nn', 'bb1 Ccg Dd Ee Nn Rr', 'bb1 Ccg Ee Nn', 'bb1 Ccg Ee Nn Rr'], maleRatio: [1, 1, 1, 1, 1, 1, 1, 1], female: ['Tri-color Mottled Chocolate Slate', 'Mottled Rusty Brown Slate', 'Tri-color Mottled Chocolate', 'Mottled Rusty Brown', 'Chocolate Red Slate', 'Chocolate Blue Red Bronze', 'Auburn', 'Red Auburn'], femaleGenotype: ['Bb1 Ccg Dd e-', 'Bb1 Ccg Dd e- Rr', 'Bb1 Ccg e-', 'Bb1 Ccg e- Rr', 'bb1 Ccg Dd e-', 'bb1 Ccg Dd e- Rr', 'bb1 Ccg e-', 'bb1 Ccg e- Rr'], femaleRatio: [1, 1, 1, 1, 1, 1, 1, 1] } },

{ sire: 'Barred Chocolate', dam: 'Blue Palm', results: { male: ['Tri-color Mottled Slate', 'Tri-color Mottled Black', 'Red Slate', 'Bronze-'], maleGenotype: ['Bb1 Ccg Dd Ee Nn', 'Bb1 Ccg Ee Nn', 'bb1 Ccg Dd Ee Nn', 'bb1 Ccg Ee Nn'], maleRatio: [1, 1, 1, 1], female: ['Tri-color Mottled Chocolate Slate', 'Tri-color Mottled Chocolate', 'Chocolate Red Slate', 'Auburn'], femaleGenotype: ['Bb1 Ccg Dd e-', 'Bb1 Ccg e-', 'bb1 Ccg Dd e-', 'bb1 Ccg e-'], femaleRatio: [1, 1, 1, 1] } },

{ sire: 'Barred Chocolate', dam: 'Blue Narragansett', results: { male: ['Barred Slate', 'Barred Black', 'Red Slate', 'Bronze'], maleGenotype: ['Bb Dd Ee Nn', 'Bb Ee Nn', 'bb Dd Ee Nn', 'bb Ee Nn'], maleRatio: [1, 1, 1, 1], female: ['Barred Chocolate Slate', 'Barred Chocolate', 'Chocolate Red Slate', 'Auburn'], femaleGenotype: ['Bb Dd e-', 'Bb e-', 'bb Dd e-', 'bb e-'], femaleRatio: [1, 1, 1, 1] } },

{ sire: 'Barred Chocolate', dam: 'Blue Red Bronze', results: { male: ['Barred Slate', 'Rusty Slate', 'Barred Black', 'Rusty Black', 'Red Slate', 'Blue Red Bronze', 'Bronze', 'Red Bronze'], maleGenotype: ['Bb Dd Ee', 'Bb Dd Ee Rr', 'Bb Ee', 'Bb Ee Rr', 'bb Dd Ee', 'bb Dd Ee Rr', 'bb Ee', 'bb Ee Rr'], maleRatio: [1, 1, 1, 1, 1, 1, 1, 1], female: ['Barred Chocolate Slate', 'Rusty Brown Slate', 'Barred Chocolate', 'Rusty Brown', 'Chocolate Red Slate', 'Chocolate Blue Red Bronze', 'Auburn', 'Red Auburn'], femaleGenotype: ['Bb Dd e-', 'Bb Dd e- Rr', 'Bb e-', 'Bb e- Rr', 'bb Dd e-', 'bb Dd e- Rr', 'bb e-', 'bb e- Rr'], femaleRatio: [1, 1, 1, 1, 1, 1, 1, 1] } },

{ sire: 'Barred Chocolate', dam: 'Blue Sweetgrass', results: { male: ['Tri-color Mottled Slate', 'Tri-color Mottled Black', 'Red Slate', 'Bronze-'], maleGenotype: ['Bb1 Ccg Dd Ee', 'Bb1 Ccg Ee', 'bb1 Ccg Dd Ee', 'bb1 Ccg Ee'], maleRatio: [1, 1, 1, 1], female: ['Tri-color Mottled Chocolate Slate', 'Tri-color Mottled Chocolate', 'Chocolate Red Slate', 'Auburn'], femaleGenotype: ['Bb1 Ccg Dd e-', 'Bb1 Ccg e-', 'bb1 Ccg Dd e-', 'bb1 Ccg e-'], femaleRatio: [1, 1, 1, 1] } },

{ sire: 'Barred Chocolate', dam: 'Bourbon Buff', results: { male: ['Rusty Black', 'Red Bronze'], maleGenotype: ['Bb Ee Nn Rr', 'bb Ee Nn Rr'], maleRatio: [1, 1], female: ['Rusty Brown', 'Red Auburn'], femaleGenotype: ['Bb e- Rr', 'bb e- Rr'], femaleRatio: [1, 1] } },

{ sire: 'Barred Chocolate', dam: 'Bourbon Red', results: { male: ['Rusty Black', 'Red Bronze'], maleGenotype: ['Bb Ee Rr', 'bb Ee Rr'], maleRatio: [1, 1], female: ['Rusty Brown', 'Red Auburn'], femaleGenotype: ['Bb e- Rr', 'bb e- Rr'], femaleRatio: [1, 1] } },

{ sire: 'Barred Chocolate', dam: 'Bronze', results: { male: ['Barred Black', 'Bronze'], maleGenotype: ['Bb Ee', 'bb Ee'], maleRatio: [1, 1], female: ['Barred Chocolate', 'Auburn'], femaleGenotype: ['Bb e-', 'bb e-'], femaleRatio: [1, 1] } },


{ sire: 'Barred Chocolate', dam: 'Chocolate', results: { male: ['Chocolate', 'Barred Chocolate'], maleGenotype: ['BB ee', 'Bb ee'], maleRatio: [1, 1], female: ['Chocolate', 'Barred Chocolate'], femaleGenotype: ['BB e-', 'Bb e-'], femaleRatio: [1, 1] } },

{ sire: 'Barred Chocolate', dam: 'Calico', results: { male: ['Tri-color Mottled Black', 'Mottled Rusty Black', 'Bronze-', 'Red Bronze.'], maleGenotype: ['Bb1 Ccg Ee Nn', 'Bb1 Ccg Ee Nn Rr', 'bb1 Ccg Ee Nn', 'bb1 Ccg Ee Nn Rr'], maleRatio: [1, 1, 1, 1], female: ['Tri-color Mottled Chocolate', 'Mottled Rusty Brown', 'Auburn', 'Red Auburn'], femaleGenotype: ['Bb1 Ccg e-', 'Bb1 Ccg e- Rr', 'bb1 Ccg e-', 'bb1 Ccg e- Rr'], femaleRatio: [1, 1, 1, 1] } },

{ sire: 'Barred Chocolate', dam: 'Chocolate Dapple', results: { male: ['Chocolate', 'Chocolate', 'Barred Chocolate', 'Barred Chocolate', 'Auburn', 'Auburn'], maleGenotype: ['BB Ccg ee Nn', 'BB Cc ee Nn', 'Bb Ccg ee Nn', 'Bb Cc ee Nn', 'bb Ccg ee Nn', 'bb Cc ee Nn'], maleRatio: [1, 1, 2, 2, 1, 1], female: ['Chocolate', 'Chocolate', 'Barred Chocolate', 'Barred Chocolate', 'Auburn', 'Auburn'], femaleGenotype: ['BB Ccg e-', 'BB Cc e-', 'Bb Ccg e-', 'Bb Cc e-', 'bb Ccg e-', 'bb Cc e-'], femaleRatio: [1, 1, 2, 2, 1, 1] } },


{ sire: 'Barred Chocolate', dam: 'Chocolate Painted', results: { male: ['Chocolate', 'Chocolate', 'Barred Chocolate', 'Barred Chocolate', 'Auburn', 'Auburn'], maleGenotype: ['BB Ccm ee', 'BB Cc ee', 'Bb Ccm ee', 'Bb Cc ee', 'bb Ccm ee', 'bb Cc ee'], maleRatio: [1, 1, 2, 2, 1, 1], female: ['Chocolate', 'Chocolate', 'Barred Chocolate', 'Barred Chocolate', 'Auburn', 'Auburn'], femaleGenotype: ['BB Ccm e-', 'BB Cc e-', 'Bb Ccm e-', 'Bb Cc e-', 'bb Ccm e-', 'bb Cc e-'], femaleRatio: [1, 1, 2, 2, 1, 1] } },


{ sire: 'Barred Chocolate', dam: 'Chocolate Palm', results: { male: ['Tri-color Mottled Chocolate', 'Auburn'], maleGenotype: ['Bb1 Ccg ee Nn', 'bb1 Ccg ee Nn'], maleRatio: [1, 1], female: ['Tri-color Mottled Chocolate', 'Auburn'], femaleGenotype: ['Bb1 Ccg e-', 'bb1 Ccg e-'], femaleRatio: [1, 1] } },

///////////////

{ sire: 'Barred Chocolate', dam: 'Slate', results: { male: ['Slate', 'Black', 'Barred Slate', 'Barred Black'], maleGenotype: ['BB Dd Ee', 'BB Ee', 'Bb Dd Ee', 'Bb Ee'], maleRatio: [12.5, 12.5, 12.5, 12.5], female: ['Chocolate Slate', 'Chocolate', 'Barred Chocolate Slate', 'Barred Chocolate'], femaleGenotype: ['BB Dd e-', 'BB e-', 'Bb Dd e-', 'Bb e-'], femaleRatio: [12.5, 12.5, 12.5, 12.5] } },

{ sire: 'Barred Chocolate', dam: 'Mottled Black', results: { male: ['Black', 'Barred Black', 'Tri-color Mottled Black', 'Bronze-'], maleGenotype: ['BB Ccg Ee Nn', 'Bb Ccg Ee Nn', 'Bb1 Ccg Ee Nn', 'bb1 Ccg Ee Nn'], maleRatio: [12.5, 12.5, 12.5, 12.5], female: ['Chocolate', 'Barred Chocolate', 'Tri-color Mottled Chocolate', 'Auburn'], femaleGenotype: ['BB Ccg e-', 'Bb Ccg e-', 'Bb1 Ccg e-', 'bb1 Ccg e-'], femaleRatio: [12.5, 12.5, 12.5, 12.5] } },

{ sire: 'Barred Chocolate', dam: 'Royal Palm', results: { male: ['Tri-color Mottled Black', 'Bronze-'], maleGenotype: ['Bb1 Ccg Ee Nn', 'bb1 Ccg Ee Nn'], maleRatio: [25, 25], female: ['Tri-color Mottled Chocolate', 'Auburn'], femaleGenotype: ['Bb1 Ccg e-', 'bb1 Ccg e-'], femaleRatio: [25, 25] } },

{ sire: 'Barred Chocolate', dam: 'Narragansett', results: { male: ['Barred Black', 'Bronze'], maleGenotype: ['Bb Ee Nn', 'bb Ee Nn'], maleRatio: [25, 25], female: ['Barred Chocolate', 'Auburn'], femaleGenotype: ['Bb e-', 'bb e-'], femaleRatio: [25, 25] } },





// PENCILLED FF ,  NOT DONE

{ sire: 'Pencilled Fall Fire', dam: 'Pencilled Blue Fall Fire', results: { male: ['Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Slate Edged Red Sweetgrass', 'Pencilled Sweetgrass', 'Pencilled Fall Fire', 'Pencilled Red Sweetgrass'], maleGenotype: ['b1b1 cgcg Dd pnpn', 'b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg Dd pnpn rr', 'b1b1 cgcg pnpn', 'b1b1 cgcg pnpn Rr', 'b1b1 cgcg pnpn rr'], maleRatio: [1, 2, 1, 1, 2, 1], female: ['Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Slate Edged Red Sweetgrass', 'Pencilled Sweetgrass', 'Pencilled Fall Fire', 'Pencilled Red Sweetgrass'], femaleGenotype: ['b1b1 cgcg Dd pnpn', 'b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg Dd pnpn rr', 'b1b1 cgcg pnpn', 'b1b1 cgcg pnpn Rr', 'b1b1 cgcg pnpn rr'], femaleRatio: [1, 2, 1, 1, 2, 1] } },




// PENCILLED SG ,  NOT DONE

{ sire: 'Pencilled Sweetgrass', dam: 'Pencilled Blue Fall Fire', results: { male: ['Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Sweetgrass', 'Pencilled Fall Fire'], maleGenotype: ['b1b1 cgcg Dd pnpn', 'b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg pnpn', 'b1b1 cgcg pnpn Rr'], maleRatio: [1, 1, 1, 1], female: ['Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Sweetgrass', 'Pencilled Fall Fire'], femaleGenotype: ['b1b1 cgcg Dd pnpn', 'b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg pnpn', 'b1b1 cgcg pnpn Rr'], femaleRatio: [1, 1, 1, 1] } },




// PENCILLED BLUE FALL FIRE CROSSES, Most common done

{ sire: 'Pencilled Blue Fall Fire', dam: 'Bronze', results: { male: ['Red Slate', 'Blue Red Bronze', 'Bronze-', 'Red Bronze'], maleGenotype: ['bb1 Ccg Dd Pnpn', 'bb1 Ccg Dd Pnpn Rr', 'bb1 Ccg Pnpn', 'bb1 Ccg Pnpn Rr'], maleRatio: [12.5, 12.5, 12.5, 12.5], female: ['Red Slate', 'Blue Red Bronze', 'Bronze-', 'Red Bronze'], femaleGenotype: ['bb1 Ccg Dd Pnpn', 'bb1 Ccg Dd Pnpn Rr', 'bb1 Ccg Pnpn', 'bb1 Ccg Pnpn Rr'], femaleRatio: [12.5, 12.5, 12.5, 12.5] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Black', results: { male: ['Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black'], maleGenotype: ['Bb1 Ccg Dd Pnpn', 'Bb1 Ccg Dd Pnpn Rr', 'Bb1 Ccg Pnpn', 'Bb1 Ccg Pnpn Rr'], maleRatio: [12.5, 12.5, 12.5, 12.5], female: ['Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black'], femaleGenotype: ['Bb1 Ccg Dd Pnpn', 'Bb1 Ccg Dd Pnpn Rr', 'Bb1 Ccg Pnpn', 'Bb1 Ccg Pnpn Rr'], femaleRatio: [12.5, 12.5, 12.5, 12.5] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Bourbon Red', results: { male: ['Blue Red Bronze', 'Slate Edged Chestnut Red', 'Red Bronze', 'Chestnut Red'], maleGenotype: ['bb1 Ccg Dd Pnpn Rr', 'bb1 Ccg Dd Pnpn rr', 'bb1 Ccg Pnpn Rr', 'bb1 Ccg Pnpn rr'], maleRatio: [12.5, 12.5, 12.5, 12.5], female: ['Blue Red Bronze', 'Slate Edged Chestnut Red', 'Red Bronze', 'Chestnut Red'], femaleGenotype: ['bb1 Ccg Dd Pnpn Rr', 'bb1 Ccg Dd Pnpn rr', 'bb1 Ccg Pnpn Rr', 'bb1 Ccg Pnpn rr'], femaleRatio: [12.5, 12.5, 12.5, 12.5] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Chocolate', results: { male: ['To be defined', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black'], maleGenotype: ['Bb1 Ccg Dd Ee Pnpn', 'Bb1 Ccg Dd Ee Pnpn Rr', 'Bb1 Ccg Ee Pnpn', 'Bb1 Ccg Ee Pnpn Rr'], maleRatio: [12.5, 12.5, 12.5, 12.5], female: ['Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black'], femaleGenotype: ['Bb1 Ccg Dd Pnpn', 'Bb1 Ccg Dd Pnpn Rr', 'Bb1 Ccg Pnpn', 'Bb1 Ccg Pnpn Rr'], femaleRatio: [12.5, 12.5, 12.5, 12.5] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Fall Fire', results: { male: ['Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Slate Edged Red Sweetgrass', 'Pencilled Sweetgrass', 'Pencilled Fall Fire', 'Pencilled Red Sweetgrass'], maleGenotype: ['b1b1 cgcg Dd Pnpn', 'b1b1 cgcg Dd Pnpn Rr', 'b1b1 cgcg Dd Pnpn rr', 'b1b1 cgcg Pnpn', 'b1b1 cgcg Pnpn Rr', 'b1b1 cgcg Pnpn rr'], maleRatio: [6.25, 12.5, 6.25, 6.25, 12.5, 6.25], female: ['Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Slate Edged Red Sweetgrass', 'Pencilled Sweetgrass', 'Pencilled Fall Fire', 'Pencilled Red Sweetgrass'], femaleGenotype: ['b1b1 cgcg Dd Pnpn', 'b1b1 cgcg Dd Pnpn Rr', 'b1b1 cgcg Dd Pnpn rr', 'b1b1 cgcg Pnpn', 'b1b1 cgcg Pnpn Rr', 'b1b1 cgcg Pnpn rr'], femaleRatio: [6.25, 12.5, 6.25, 6.25, 12.5, 6.25] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Golden Narragansett', results: { male: ['Red Slate', 'Blue Red Bronze', 'To be defined', 'Bronze-', 'Red Bronze', 'Chestnut Red'], maleGenotype: ['bb1 Ccg Dd Nn Pnpn', 'bb1 Ccg Dd Nn Pnpn Rr', 'bb1 Ccg Dd Nn Pnpn rr', 'bb1 Ccg Nn Pnpn', 'bb1 Ccg Nn Pnpn Rr', 'bb1 Ccg Nn Pnpn rr'], maleRatio: [6.25, 12.5, 6.25, 6.25, 12.5, 6.25], female: ['Red Slate', 'Blue Red Bronze', 'Slate Edged Chestnut Red', 'Bronze-', 'Red Bronze', 'Chestnut Red'], femaleGenotype: ['bb1 Ccg Dd Pnpn', 'bb1 Ccg Dd Pnpn Rr', 'bb1 Ccg Dd Pnpn rr', 'bb1 Ccg Pnpn', 'bb1 Ccg Pnpn Rr', 'bb1 Ccg Pnpn rr'], femaleRatio: [6.25, 12.5, 6.25, 6.25, 12.5, 6.25] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Blue Red Bronze', results: { male: ['Lilac', 'Lavender Red Bronze', 'Lavender Edged Chestnut Red', 'Red Slate', 'Blue Red Bronze', 'Slate Edged Chestnut Red', 'Bronze-', 'Red Bronze', 'Chestnut Red'], maleGenotype: ['bb1 Ccg DD Pnpn', 'bb1 Ccg DD Pnpn Rr', 'bb1 Ccg DD Pnpn rr', 'bb1 Ccg Dd Pnpn', 'bb1 Ccg Dd Pnpn Rr', 'bb1 Ccg Dd Pnpn rr', 'bb1 Ccg Pnpn', 'bb1 Ccg Pnpn Rr', 'bb1 Ccg Pnpn rr'], maleRatio: [3.125, 6.25, 3.125, 6.25, 12.5, 6.25, 3.125, 6.25, 3.125], female: ['Lilac', 'Lavender Red Bronze', 'Lavender Edged Chestnut Red', 'Red Slate', 'Blue Red Bronze', 'Slate Edged Chestnut Red', 'Bronze-', 'Red Bronze', 'Chestnut Red'], femaleGenotype: ['bb1 Ccg DD Pnpn', 'bb1 Ccg DD Pnpn Rr', 'bb1 Ccg DD Pnpn rr', 'bb1 Ccg Dd Pnpn', 'bb1 Ccg Dd Pnpn Rr', 'bb1 Ccg Dd Pnpn rr', 'bb1 Ccg Pnpn', 'bb1 Ccg Pnpn Rr', 'bb1 Ccg Pnpn rr'], femaleRatio: [3.125, 6.25, 3.125, 6.25, 12.5, 6.25, 3.125, 6.25, 3.125] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Pencilled Blue Fall Fire', results: { male: ['Pencilled Lavender Sweetgrass', 'Pencilled Lavender Fall Fire', 'Pencilled Lavender Edged Red Sweetgrass', 'Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Slate Edged Red Sweetgrass', 'Pencilled Sweetgrass', 'Pencilled Fall Fire', 'Pencilled Red Sweetgrass'], maleGenotype: ['b1b1 cgcg DD pnpn', 'b1b1 cgcg DD pnpn Rr', 'b1b1 cgcg DD pnpn rr', 'b1b1 cgcg Dd pnpn', 'b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg Dd pnpn rr', 'b1b1 cgcg pnpn', 'b1b1 cgcg pnpn Rr', 'b1b1 cgcg pnpn rr'], maleRatio: [3.125, 6.25, 3.125, 6.25, 12.5, 6.25, 3.125, 6.25, 3.125], female: ['Pencilled Lavender Sweetgrass', 'Pencilled Lavender Fall Fire', 'Pencilled Lavender Edged Red Sweetgrass', 'Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Slate Edged Red Sweetgrass', 'Pencilled Sweetgrass', 'Pencilled Fall Fire', 'Pencilled Red Sweetgrass'], femaleGenotype: ['b1b1 cgcg DD pnpn', 'b1b1 cgcg DD pnpn Rr', 'b1b1 cgcg DD pnpn rr', 'b1b1 cgcg Dd pnpn', 'b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg Dd pnpn rr', 'b1b1 cgcg pnpn', 'b1b1 cgcg pnpn Rr', 'b1b1 cgcg pnpn rr'], femaleRatio: [3.125, 6.25, 3.125, 6.25, 12.5, 6.25, 3.125, 6.25, 3.125] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Pencilled Fall Fire', results: { male: ['Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Slate Edged Red Sweetgrass', 'Pencilled Sweetgrass', 'Pencilled Fall Fire', 'Pencilled Red Sweetgrass'], maleGenotype: ['b1b1 cgcg Dd pnpn', 'b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg Dd pnpn rr', 'b1b1 cgcg pnpn', 'b1b1 cgcg pnpn Rr', 'b1b1 cgcg pnpn rr'], maleRatio: [6.25, 12.5, 6.25, 6.25, 12.5, 6.25], female: ['Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Slate Edged Red Sweetgrass', 'Pencilled Sweetgrass', 'Pencilled Fall Fire', 'Pencilled Red Sweetgrass'], femaleGenotype: ['b1b1 cgcg Dd pnpn', 'b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg Dd pnpn rr', 'b1b1 cgcg pnpn', 'b1b1 cgcg pnpn Rr', 'b1b1 cgcg pnpn rr'], femaleRatio: [6.25, 12.5, 6.25, 6.25, 12.5, 6.25] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Pencilled Blue Sweetgrass', results: { male: ['Pencilled Lavender Sweetgrass', 'Pencilled Lavender Fall Fire', 'Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Sweetgrass', 'Pencilled Fall Fire'], maleGenotype: ['b1b1 cgcg DD pnpn', 'b1b1 cgcg DD pnpn Rr', 'b1b1 cgcg Dd pnpn', 'b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg pnpn', 'b1b1 cgcg pnpn Rr'], maleRatio: [6.25, 6.25, 12.5, 12.5, 6.25, 6.25], female: ['Pencilled Lavender Sweetgrass', 'Pencilled Lavender Fall Fire', 'Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Sweetgrass', 'Pencilled Fall Fire'], femaleGenotype: ['b1b1 cgcg DD pnpn', 'b1b1 cgcg DD pnpn Rr', 'b1b1 cgcg Dd pnpn', 'b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg pnpn', 'b1b1 cgcg pnpn Rr'], femaleRatio: [6.25, 6.25, 12.5, 12.5, 6.25, 6.25] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Pencilled Sweetgrass', results: { male: ['Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Sweetgrass', 'Pencilled Fall Fire'], maleGenotype: ['b1b1 cgcg Dd pnpn', 'b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg pnpn', 'b1b1 cgcg pnpn Rr'], maleRatio: [12.5, 12.5, 12.5, 12.5], female: ['Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Sweetgrass', 'Pencilled Fall Fire'], femaleGenotype: ['b1b1 cgcg Dd pnpn', 'b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg pnpn', 'b1b1 cgcg pnpn Rr'], femaleRatio: [12.5, 12.5, 12.5, 12.5] } },


{ sire: 'Pencilled Blue Fall Fire', dam: 'Chocolate Painted', results: { male: ['Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black', 'Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black', 'Red Slate', 'Blue Red Bronze.', 'Bronze-', 'Red Bronze', 'Red Slate', 'Blue Red Bronze.', 'Bronze-', 'Red Bronze'], maleGenotype: ['Bb1 cgcm Dd Ee pnpn', 'Bb1 cgcm Dd Ee pnpn Rr', 'Bb1 cgcm Ee pnpn', 'Bb1 cgcm Ee pnpn Rr', 'Bb1 cgc Dd Ee pnpn', 'Bb1 cgc Dd Ee pnpn Rr', 'Bb1 cgc Ee pnpn', 'Bb1 cgc Ee pnpn Rr', 'bb1 cgcm Dd Ee pnpn', 'bb1 cgcm Dd Ee pnpn Rr', 'bb1 cgcm Ee pnpn', 'bb1 cgcm Ee pnpn Rr', 'bb1 cgc Dd Ee pnpn', 'bb1 cgc Dd Ee pnpn Rr', 'bb1 cgc Ee pnpn', 'bb1 cgc Ee pnpn Rr'], maleRatio: [3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125], female: ['Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black', 'Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black', 'Red Slate', 'Blue Red Bronze.', 'Bronze-', 'Red Bronze.', 'Red Slate', 'Blue Red Bronze.', 'Bronze-', 'Red Bronze.'], femaleGenotype: ['Bb1 cgcm Dd pnpn', 'Bb1 cgcm Dd pnpn Rr', 'Bb1 cgcm pnpn', 'Bb1 cgcm pnpn Rr', 'Bb1 cgc Dd pnpn', 'Bb1 cgc Dd pnpn Rr', 'Bb1 cgc pnpn', 'Bb1 cgc pnpn Rr', 'bb1 cgcm Dd pnpn', 'bb1 cgcm Dd pnpn Rr', 'bb1 cgcm pnpn', 'bb1 cgcm pnpn Rr', 'bb1 cgc Dd pnpn', 'bb1 cgc Dd pnpn Rr', 'bb1 cgc pnpn', 'bb1 cgc pnpn Rr'], femaleRatio: [3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Grizzled Chocolate Painted', results: { male: ['Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black', 'Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black'], maleGenotype: ['Bb1 cgcm Dd Ee pnpn', 'Bb1 cgcm Dd Ee pnpn Rr', 'Bb1 cgcm Ee pnpn', 'Bb1 cgcm Ee pnpn Rr', 'Bb1 cgc Dd Ee pnpn', 'Bb1 cgc Dd Ee pnpn Rr', 'Bb1 cgc Ee pnpn', 'Bb1 cgc Ee pnpn Rr'], maleRatio: [6.25, 6.25, 6.25, 6.25, 6.25, 6.25, 6.25, 6.25], female: ['Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black', 'Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black'], femaleGenotype: ['Bb1 cgcm Dd pnpn', 'Bb1 cgcm Dd pnpn Rr', 'Bb1 cgcm pnpn', 'Bb1 cgcm pnpn Rr', 'Bb1 cgc Dd pnpn', 'Bb1 cgc Dd pnpn Rr', 'Bb1 cgc pnpn', 'Bb1 cgc pnpn Rr'], femaleRatio: [6.25, 6.25, 6.25, 6.25, 6.25, 6.25, 6.25, 6.25] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Grizzled Black Painted', results: { male: ['Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black', 'Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black'], maleGenotype: ['Bb1 cgcm Dd pnpn', 'Bb1 cgcm Dd pnpn Rr', 'Bb1 cgcm pnpn', 'Bb1 cgcm pnpn Rr', 'Bb1 cgc Dd pnpn', 'Bb1 cgc Dd pnpn Rr', 'Bb1 cgc pnpn', 'Bb1 cgc pnpn Rr'], maleRatio: [6.25, 6.25, 6.25, 6.25, 6.25, 6.25, 6.25, 6.25], female: ['Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black', 'Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black'], femaleGenotype: ['Bb1 cgcm Dd pnpn', 'Bb1 cgcm Dd pnpn Rr', 'Bb1 cgcm pnpn', 'Bb1 cgcm pnpn Rr', 'Bb1 cgc Dd pnpn', 'Bb1 cgc Dd pnpn Rr', 'Bb1 cgc pnpn', 'Bb1 cgc pnpn Rr'], femaleRatio: [6.25, 6.25, 6.25, 6.25, 6.25, 6.25, 6.25, 6.25] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Painted-', results: { male: ['Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black', 'Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black'], maleGenotype: ['Bb1 cgcm Dd pnpn', 'Bb1 cgcm Dd pnpn Rr', 'Bb1 cgcm pnpn', 'Bb1 cgcm pnpn Rr', 'Bb1 cgc Dd pnpn', 'Bb1 cgc Dd pnpn Rr', 'Bb1 cgc pnpn', 'Bb1 cgc pnpn Rr'], maleRatio: [3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125], female: ['Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black', 'Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black'], femaleGenotype: ['Bb1 cgcm Dd pnpn', 'Bb1 cgcm Dd pnpn Rr', 'Bb1 cgcm pnpn', 'Bb1 cgcm pnpn Rr', 'Bb1 cgc Dd pnpn', 'Bb1 cgc Dd pnpn Rr', 'Bb1 cgc pnpn', 'Bb1 cgc pnpn Rr'], femaleRatio: [3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125, 3.125] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Slate Painted', results: { male: ['Tri-color Mottled Lavender', 'Mottled Rusty Lavender', 'Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black', 'Tri-color Mottled Lavender', 'Mottled Rusty Lavender', 'Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black'], maleGenotype: ['Bb1 cgcm DD pnpn', 'Bb1 cgcm DD pnpn Rr', 'Bb1 cgcm Dd pnpn', 'Bb1 cgcm Dd pnpn Rr', 'Bb1 cgcm pnpn', 'Bb1 cgcm pnpn Rr', 'Bb1 cgc DD pnpn', 'Bb1 cgc DD pnpn Rr', 'Bb1 cgc Dd pnpn', 'Bb1 cgc Dd pnpn Rr', 'Bb1 cgc pnpn', 'Bb1 cgc pnpn Rr'], maleRatio: [1.5625, 1.5625, 3.125, 3.125, 1.5625, 1.5625, 1.5625, 1.5625, 3.125, 3.125, 1.5625, 1.5625], female: ['Tri-color Mottled Lavender', 'Mottled Rusty Lavender', 'Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black', 'Tri-color Mottled Lavender', 'Mottled Rusty Lavender', 'Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black'], femaleGenotype: ['Bb1 cgcm DD pnpn', 'Bb1 cgcm DD pnpn Rr', 'Bb1 cgcm Dd pnpn', 'Bb1 cgcm Dd pnpn Rr', 'Bb1 cgcm pnpn', 'Bb1 cgcm pnpn Rr', 'Bb1 cgc DD pnpn', 'Bb1 cgc DD pnpn Rr', 'Bb1 cgc Dd pnpn', 'Bb1 cgc Dd pnpn Rr', 'Bb1 cgc pnpn', 'Bb1 cgc pnpn Rr'], femaleRatio: [1.5625, 1.5625, 3.125, 3.125, 1.5625, 1.5625, 1.5625, 1.5625, 3.125, 3.125, 1.5625, 1.5625] } },


{ sire: 'Pencilled Blue Fall Fire', dam: 'Pencilled Red Sweetgrass', results: { male: ['Pencilled Blue Fall Fire', 'Pencilled Slate Edged Red Sweetgrass', 'Pencilled Fall Fire', 'Pencilled Red Sweetgrass'], maleGenotype: ['b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg Dd pnpn rr', 'b1b1 cgcg pnpn Rr', 'b1b1 cgcg pnpn rr'], maleRatio: [12.5, 12.5, 12.5, 12.5], female: ['Pencilled Blue Fall Fire', 'Pencilled Slate Edged Red Sweetgrass', 'Pencilled Fall Fire', 'Pencilled Red Sweetgrass'], femaleGenotype: ['b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg Dd pnpn rr', 'b1b1 cgcg pnpn Rr', 'b1b1 cgcg pnpn rr'], femaleRatio: [12.5, 12.5, 12.5, 12.5] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Pencilled Red Palm', results: { male: ['Pencilled Blue Fall Fire', 'Pencilled Slate Edged Red Sweetgrass', 'Pencilled Fall Fire', 'Pencilled Red Sweetgrass'], maleGenotype: ['b1b1 cgcg Dd Nn pnpn Rr', 'b1b1 cgcg Dd Nn pnpn rr', 'b1b1 cgcg Nn pnpn Rr', 'b1b1 cgcg Nn pnpn rr'], maleRatio: [12.5, 12.5, 12.5, 12.5], female: ['Pencilled Blue Fall Fire', 'Pencilled Slate Edged Red Sweetgrass', 'Pencilled Fall Fire', 'Pencilled Red Sweetgrass'], femaleGenotype: ['b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg Dd pnpn rr', 'b1b1 cgcg pnpn Rr', 'b1b1 cgcg pnpn rr'], femaleRatio: [12.5, 12.5, 12.5, 12.5] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Pencilled Lavender Fall Fire', results: { male: ['Pencilled Lavender Sweetgrass', 'Pencilled Lavender Fall Fire', 'Pencilled Lavender Edged Red Sweetgrass', 'Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Slate Edged Red Sweetgrass'], maleGenotype: ['b1b1 cgcg DD pnpn', 'b1b1 cgcg DD pnpn Rr', 'b1b1 cgcg DD pnpn rr', 'b1b1 cgcg Dd pnpn', 'b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg Dd pnpn rr'], maleRatio: [6.25, 12.5, 6.25, 6.25, 12.5, 6.25], female: ['Pencilled Lavender Sweetgrass', 'Pencilled Lavender Fall Fire', 'Pencilled Lavender Edged Red Sweetgrass', 'Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Slate Edged Red Sweetgrass'], femaleGenotype: ['b1b1 cgcg DD pnpn', 'b1b1 cgcg DD pnpn Rr', 'b1b1 cgcg DD pnpn rr', 'b1b1 cgcg Dd pnpn', 'b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg Dd pnpn rr'], femaleRatio: [6.25, 12.5, 6.25, 6.25, 12.5, 6.25] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Tri-color Pencilled Blue Palm', results: { male: ['Pencilled Lavender Sweetgrass', 'Pencilled Lavender Fall Fire', 'Pencilled Lavender Edged Red Sweetgrass', 'Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Slate Edged Red Sweetgrass', 'Pencilled Sweetgrass', 'Pencilled Fall Fire', 'Pencilled Red Sweetgrass'], maleGenotype: ['b1b1 cgcg DD Nn pnpn', 'b1b1 cgcg DD Nn pnpn Rr', 'b1b1 cgcg DD Nn pnpn rr', 'b1b1 cgcg Dd Nn pnpn', 'b1b1 cgcg Dd Nn pnpn Rr', 'b1b1 cgcg Dd Nn pnpn rr', 'b1b1 cgcg Nn pnpn', 'b1b1 cgcg Nn pnpn Rr', 'b1b1 cgcg Nn pnpn rr'], maleRatio: [3.125, 6.25, 3.125, 6.25, 12.5, 6.25, 3.125, 6.25, 3.125], female: ['Pencilled Lavender Sweetgrass', 'Pencilled Lavender Fall Fire', 'Pencilled Lavender Edged Red Sweetgrass', 'Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Slate Edged Red Sweetgrass', 'Pencilled Sweetgrass', 'Pencilled Fall Fire', 'Pencilled Red Sweetgrass'], femaleGenotype: ['b1b1 cgcg DD pnpn', 'b1b1 cgcg DD pnpn Rr', 'b1b1 cgcg DD pnpn rr', 'b1b1 cgcg Dd pnpn', 'b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg Dd pnpn rr', 'b1b1 cgcg pnpn', 'b1b1 cgcg pnpn Rr', 'b1b1 cgcg pnpn rr'], femaleRatio: [3.125, 6.25, 3.125, 6.25, 12.5, 6.25, 3.125, 6.25, 3.125] } },


{ sire: 'Pencilled Blue Fall Fire', dam: 'Lavender', results: { male: ['Tri-color Mottled Lavender', 'Mottled Rusty Lavender', 'Tri-color Mottled Slate', 'Mottled Rusty Slate'], maleGenotype: ['Bb1 Ccg DD Pnpn', 'Bb1 Ccg DD Pnpn Rr', 'Bb1 Ccg Dd Pnpn', 'Bb1 Ccg Dd Pnpn Rr'], maleRatio: [12.5, 12.5, 12.5, 12.5], female: ['Tri-color Mottled Lavender', 'Mottled Rusty Lavender', 'Tri-color Mottled Slate', 'Mottled Rusty Slate'], femaleGenotype: ['Bb1 Ccg DD Pnpn', 'Bb1 Ccg DD Pnpn Rr', 'Bb1 Ccg Dd Pnpn', 'Bb1 Ccg Dd Pnpn Rr'], femaleRatio: [12.5, 12.5, 12.5, 12.5] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Mottled Black', results: { male: ['Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black', 'Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire.', 'Pencilled Sweetgrass.', 'Pencilled Fall Fire.'], maleGenotype: ['Bb1 cgcg Dd Nn Pnpn', 'Bb1 cgcg Dd Nn Pnpn Rr', 'Bb1 cgcg Nn Pnpn', 'Bb1 cgcg Nn Pnpn Rr', 'b1b1 cgcg Dd Nn Pnpn', 'b1b1 cgcg Dd Nn Pnpn Rr', 'b1b1 cgcg Nn Pnpn', 'b1b1 cgcg Nn Pnpn Rr'], maleRatio: [6.25, 6.25, 6.25, 6.25, 6.25, 6.25, 6.25, 6.25], female: ['Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black', 'Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire.', 'Pencilled Sweetgrass.', 'Pencilled Fall Fire.'], femaleGenotype: ['Bb1 cgcg Dd Pnpn', 'Bb1 cgcg Dd Pnpn Rr', 'Bb1 cgcg Pnpn', 'Bb1 cgcg Pnpn Rr', 'b1b1 cgcg Dd Pnpn', 'b1b1 cgcg Dd Pnpn Rr', 'b1b1 cgcg Pnpn', 'b1b1 cgcg Pnpn Rr'], femaleRatio: [6.25, 6.25, 6.25, 6.25, 6.25, 6.25, 6.25, 6.25] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Narragansett', results: { male: ['Red Slate', 'Blue Red Bronze.', 'Bronze-', 'Red Bronze.'], maleGenotype: ['bb1 Ccg Dd Nn Pnpn', 'bb1 Ccg Dd Nn Pnpn Rr', 'bb1 Ccg Nn Pnpn', 'bb1 Ccg Nn Pnpn Rr'], maleRatio: [12.5, 12.5, 12.5, 12.5], female: ['Red Slate', 'Blue Red Bronze.', 'Bronze-', 'Red Bronze.'], femaleGenotype: ['bb1 Ccg Dd Pnpn', 'bb1 Ccg Dd Pnpn Rr', 'bb1 Ccg Pnpn', 'bb1 Ccg Pnpn Rr'], femaleRatio: [12.5, 12.5, 12.5, 12.5] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Pencilled Palm', results: { male: ['Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Sweetgrass', 'Pencilled Fall Fire'], maleGenotype: ['b1b1 cgcg Dd Nn Pnpn', 'b1b1 cgcg Dd Nn Pnpn Rr', 'b1b1 cgcg Nn Pnpn', 'b1b1 cgcg Nn Pnpn Rr'], maleRatio: [12.5, 12.5, 12.5, 12.5], female: ['Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Sweetgrass', 'Pencilled Fall Fire'], femaleGenotype: ['b1b1 cgcg Dd Pnpn', 'b1b1 cgcg Dd Pnpn Rr', 'b1b1 cgcg Pnpn', 'b1b1 cgcg Pnpn Rr'], femaleRatio: [12.5, 12.5, 12.5, 12.5] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Royal Palm', results: { male: ['Pencilled Blue Sweeetgrass', 'Pencilled Blue Fall Fire.', 'Pencilled Sweetgrass.', 'Pencilled Fall Fire.'], maleGenotype: ['b1b1 cgcg Dd Nn Pnpn', 'b1b1 cgcg Dd Nn Pnpn Rr', 'b1b1 cgcg Nn Pnpn', 'b1b1 cgcg Nn Pnpn Rr'], maleRatio: [12.5, 12.5, 12.5, 12.5], female: ['Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire.', 'Pencilled Sweetgrass.', 'Pencilled Fall Fire.'], femaleGenotype: ['b1b1 cgcg Dd Pnpn', 'b1b1 cgcg Dd Pnpn Rr', 'b1b1 cgcg Pnpn', 'b1b1 cgcg Pnpn Rr'], femaleRatio: [12.5, 12.5, 12.5, 12.5] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Recessive Slate', results: { male: ['Red Slate', 'Blue Red Bronze.', 'Bronze-', 'Red Bronze.'], maleGenotype: ['bb1 Ccg Dd Pnpn Slsl', 'bb1 Ccg Dd Pnpn Rr Slsl', 'bb1 Ccg Pnpn Slsl', 'bb1 Ccg Pnpn Rr Slsl'], maleRatio: [12.5, 12.5, 12.5, 12.5], female: ['Red Slate', 'Blue Red Bronze.', 'Bronze-', 'Red Bronze.'], femaleGenotype: ['bb1 Ccg Dd Pnpn Slsl', 'bb1 Ccg Dd Pnpn Rr Slsl', 'bb1 Ccg Pnpn Slsl', 'bb1 Ccg Pnpn Rr Slsl'], femaleRatio: [12.5, 12.5, 12.5, 12.5] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Rusty Black', results: { male: ['Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Slate Edged Barred Jersey Buff', 'Tri-color Mottled Black', 'Mottled Rusty Black', 'Barred Jersey Buff', 'Red Slate', 'Blue Red Bronze.', 'Slate Edged Chestnut Red', 'Bronze-', 'Red Bronze.', 'Chestnut Red'], maleGenotype: ['Bb1 Ccg Dd Pnpn', 'Bb1 Ccg Dd Pnpn Rr', 'Bb1 Ccg Dd Pnpn rr', 'Bb1 Ccg Pnpn', 'Bb1 Ccg Pnpn Rr', 'Bb1 Ccg Pnpn rr', 'bb1 Ccg Dd Pnpn', 'bb1 Ccg Dd Pnpn Rr', 'bb1 Ccg Dd Pnpn rr', 'bb1 Ccg Pnpn', 'bb1 Ccg Pnpn Rr', 'bb1 Ccg Pnpn rr'], maleRatio: [3.125, 6.25, 3.125, 3.125, 6.25, 3.125, 3.125, 6.25, 3.125, 3.125, 6.25, 3.125], female: ['Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Slate Edged Barred Jersey Buff', 'Tri-color Mottled Black', 'Mottled Rusty Black', 'Barred Jersey Buff', 'Red Slate', 'Blue Red Bronze.', 'Slate Edged Chestnut Red', 'Bronze-', 'Red Bronze.', 'Chestnut Red'], femaleGenotype: ['Bb1 Ccg Dd Pnpn', 'Bb1 Ccg Dd Pnpn Rr', 'Bb1 Ccg Dd Pnpn rr', 'Bb1 Ccg Pnpn', 'Bb1 Ccg Pnpn Rr', 'Bb1 Ccg Pnpn rr', 'bb1 Ccg Dd Pnpn', 'bb1 Ccg Dd Pnpn Rr', 'bb1 Ccg Dd Pnpn rr', 'bb1 Ccg Pnpn', 'bb1 Ccg Pnpn Rr', 'bb1 Ccg Pnpn rr'], femaleRatio: [3.125, 6.25, 3.125, 3.125, 6.25, 3.125, 3.125, 6.25, 3.125, 3.125, 6.25, 3.125] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Red Bronze', results: { male: ['Red Slate', 'Blue Red Bronze.', 'Slate Edged Chestnut Red', 'Bronze-', 'Red Bronze.', 'Chestnut Red'], maleGenotype: ['bb1 Ccg Dd Pnpn', 'bb1 Ccg Dd Pnpn Rr', 'bb1 Ccg Dd Pnpn rr', 'bb1 Ccg Pnpn', 'bb1 Ccg Pnpn Rr', 'bb1 Ccg Pnpn rr'], maleRatio: [6.25, 12.5, 6.25, 6.25, 12.5, 6.25], female: ['Red Slate', 'Blue Red Bronze.', 'Slate Edged Chestnut Red', 'Bronze-', 'Red Bronze.', 'Chestnut Red'], femaleGenotype: ['bb1 Ccg Dd Pnpn', 'bb1 Ccg Dd Pnpn Rr', 'bb1 Ccg Dd Pnpn rr', 'bb1 Ccg Pnpn', 'bb1 Ccg Pnpn Rr', 'bb1 Ccg Pnpn rr'], femaleRatio: [6.25, 12.5, 6.25, 6.25, 12.5, 6.25] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Slate', results: { male: ['Tri-color Mottled Lavender', 'Mottled Rusty Lavender', 'Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black'], maleGenotype: ['Bb1 Ccg DD Pnpn', 'Bb1 Ccg DD Pnpn Rr', 'Bb1 Ccg Dd Pnpn', 'Bb1 Ccg Dd Pnpn Rr', 'Bb1 Ccg Pnpn', 'Bb1 Ccg Pnpn Rr'], maleRatio: [6.25, 6.25, 12.5, 12.5, 6.25, 6.25], female: ['Tri-color Mottled Lavender', 'Mottled Rusty Lavender', 'Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black'], femaleGenotype: ['Bb1 Ccg DD Pnpn', 'Bb1 Ccg DD Pnpn Rr', 'Bb1 Ccg Dd Pnpn', 'Bb1 Ccg Dd Pnpn Rr', 'Bb1 Ccg Pnpn', 'Bb1 Ccg Pnpn Rr'], femaleRatio: [6.25, 6.25, 12.5, 12.5, 6.25, 6.25] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Red Slate', results: { male: ['Lilac', 'Lavender Red Bronze', 'Red Slate', 'Blue Red Bronze.', 'Bronze-', 'Red Bronze.'], maleGenotype: ['bb1 Ccg DD Pnpn', 'bb1 Ccg DD Pnpn Rr', 'bb1 Ccg Dd Pnpn', 'bb1 Ccg Dd Pnpn Rr', 'bb1 Ccg Pnpn', 'bb1 Ccg Pnpn Rr'], maleRatio: [6.25, 6.25, 12.5, 12.5, 6.25, 6.25], female: ['Lilac', 'Lavender Red Bronze', 'Red Slate', 'Blue Red Bronze.', 'Bronze-', 'Red Bronze.'], femaleGenotype: ['bb1 Ccg DD Pnpn', 'bb1 Ccg DD Pnpn Rr', 'bb1 Ccg Dd Pnpn', 'bb1 Ccg Dd Pnpn Rr', 'bb1 Ccg Pnpn', 'bb1 Ccg Pnpn Rr'], femaleRatio: [6.25, 6.25, 12.5, 12.5, 6.25, 6.25] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Sweetgrass', results: { male: ['Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire.', 'Pencilled Sweetgrass.', 'Pencilled Fall Fire.'], maleGenotype: ['b1b1 cgcg Dd Pnpn', 'b1b1 cgcg Dd Pnpn Rr', 'b1b1 cgcg Pnpn', 'b1b1 cgcg Pnpn Rr'], maleRatio: [12.5, 12.5, 12.5, 12.5], female: ['Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire.', 'Pencilled Sweetgrass.', 'Pencilled Fall Fire.'], femaleGenotype: ['b1b1 cgcg Dd Pnpn', 'b1b1 cgcg Dd Pnpn Rr', 'b1b1 cgcg Pnpn', 'b1b1 cgcg Pnpn Rr'], femaleRatio: [12.5, 12.5, 12.5, 12.5] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Tiger Bronze', results: { male: ['Tiger Blue', 'Pencilled Blue Red Phoenix', 'Tiger Bronze', 'Pencilled Red Phoenix', 'Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Sweetgrass', 'Pencilled Fall Fire'], maleGenotype: ['b1b1 Ccg Dd pnpn', 'b1b1 Ccg Dd pnpn Rr', 'b1b1 Ccg pnpn', 'b1b1 Ccg pnpn Rr', 'b1b1 cgcg Dd pnpn', 'b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg pnpn', 'b1b1 cgcg pnpn Rr'], maleRatio: [6.25, 6.25, 6.25, 6.25, 6.25, 6.25, 6.25, 6.25], female: ['Tiger Blue', 'Pencilled Blue Red Phoenix', 'Tiger Bronze', 'Pencilled Red Phoenix', 'Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Sweetgrass', 'Pencilled Fall Fire'], femaleGenotype: ['b1b1 Ccg Dd pnpn', 'b1b1 Ccg Dd pnpn Rr', 'b1b1 Ccg pnpn', 'b1b1 Ccg pnpn Rr', 'b1b1 cgcg Dd pnpn', 'b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg pnpn', 'b1b1 cgcg pnpn Rr'], femaleRatio: [6.25, 6.25, 6.25, 6.25, 6.25, 6.25, 6.25, 6.25] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'Tri-color Pencilled Palm', results: { male: ['Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Slate Edged Red Sweetgrass', 'Pencilled Sweetgrass', 'Pencilled Fall Fire', 'Pencilled Red Sweetgrass'], maleGenotype: ['b1b1 cgcg Dd Nn pnpn', 'b1b1 cgcg Dd Nn pnpn Rr', 'b1b1 cgcg Dd Nn pnpn rr', 'b1b1 cgcg Nn pnpn', 'b1b1 cgcg Nn pnpn Rr', 'b1b1 cgcg Nn pnpn rr'], maleRatio: [6.25, 12.5, 6.25, 6.25, 12.5, 6.25], female: ['Pencilled Blue Sweetgrass', 'Pencilled Blue Fall Fire', 'Pencilled Slate Edged Red Sweetgrass', 'Pencilled Sweetgrass', 'Pencilled Fall Fire', 'Pencilled Red Sweetgrass'], femaleGenotype: ['b1b1 cgcg Dd pnpn', 'b1b1 cgcg Dd pnpn Rr', 'b1b1 cgcg Dd pnpn rr', 'b1b1 cgcg pnpn', 'b1b1 cgcg pnpn Rr', 'b1b1 cgcg pnpn rr'], femaleRatio: [6.25, 12.5, 6.25, 6.25, 12.5, 6.25] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'White (Dark Brown Eyes)', results: { male: ['Red Slate', 'Blue Red Bronze', 'Bronze-', 'Red Bronze'], maleGenotype: ['bb1 cgc Dd Pnpn', 'bb1 cgc Dd Pnpn Rr', 'bb1 cgc Pnpn', 'bb1 cgc Pnpn Rr'], maleRatio: [12.5, 12.5, 12.5, 12.5], female: ['Red Slate', 'Blue Red Bronze', 'Bronze-', 'Red Bronze'], femaleGenotype: ['bb1 cgc Dd Pnpn', 'bb1 cgc Dd Pnpn Rr', 'bb1 cgc Pnpn', 'bb1 cgc Pnpn Rr'], femaleRatio: [12.5, 12.5, 12.5, 12.5] } },

{ sire: 'Pencilled Blue Fall Fire', dam: 'White (Blue Eyes)', results: { male: ['Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black'], maleGenotype: ['Bb1 cgc Dd Pnpn', 'Bb1 cgc Dd Pnpn Rr', 'Bb1 cgc Pnpn', 'Bb1 cgc Pnpn Rr'], maleRatio: [12.5, 12.5, 12.5, 12.5], female: ['Tri-color Mottled Slate', 'Mottled Rusty Slate', 'Tri-color Mottled Black', 'Mottled Rusty Black'], femaleGenotype: ['Bb1 cgc Dd Pnpn', 'Bb1 cgc Dd Pnpn Rr', 'Bb1 cgc Pnpn', 'Bb1 cgc Pnpn Rr'], femaleRatio: [12.5, 12.5, 12.5, 12.5] } },




];









