const sireVarieties = [
  { name: 'Auburn', genotype: 'bb ee' },
  { name: 'Barred Black', genotype: 'Bb' },
  { name: 'Barred Black Tuxedo', genotype: 'Bb cmcm' },
  { name: 'Barred Chocolate', genotype: 'Bb ee' },
  { name: 'Barred Chocolate Tuxedo', genotype: 'Bb cmcm ee' },
  { name: 'Barred Recessive Blue Tuxedo', genotype: 'Bb cmcm slsl'},
  { name: 'Barred Slate', genotype: 'Bb Dd' },
  { name: 'Black', genotype: 'BB' },
  { name: 'Black Tuxedo', genotype: 'BB cmcm' },
  { name: 'Black Winged Bronze', genotype: 'b1b1' },
  { name: 'Black Winged Narragansett', genotype: 'b1b1 nn' },
  { name: 'Blue Calico', genotype: 'b1b1 cgcg Dd nn' },
  { name: 'Blue Cornish Palm', genotype: 'b1b1 Ccg Dd' },
  { name: 'Blue Fall Fire', genotype: 'b1b1 cgcg Dd Rr'},
  { name: 'Blue Narragansett', genotype: 'bb Dd nn' },
  { name: 'Blue Palm', genotype: 'b1b1 cgcg Dd nn' },
  { name: 'Blue Red Bronze', genotype: 'bb Dd Rr' },
  { name: 'Blue Sweetgrass', genotype: 'b1b1 cgcg Dd' },
  { name: 'Blue Cornish Palm', genotype: 'b1b1 Ccg Dd' },
  { name: 'Bourbon Buff', genotype: 'bb nn rr' },
  { name: 'Bourbon Red', genotype: 'bb rr' },
  { name: 'Bronze', genotype: 'bb' },
  { name: 'Brown Winged Golden Silver Auburn', genotype: 'b1b1 ee nn Rr'},
  { name: 'Calico', genotype: 'b1b1 cgcg nn Rr' },
  { name: 'Chestnut Buff', genotype: 'bb1 nn rr' },
  { name: 'Chestnut Red', genotype: 'bb1 rr' },
  { name: 'Chocolate', genotype: 'BB ee' },
  { name: 'Chocolate Dapple', genotype: 'Bb cgc ee nn' },
  { name: 'Chocolate Fawn', genotype: 'bb cmc ee'},
  { name: 'Chocolate Painted (Split Bronze)', genotype: 'Bb cmc ee'},
  { name: 'Chocolate Painted (Split Black Winged Bronze)', genotype: 'Bb1 cmc ee'},
  { name: 'Chocolate Palm', genotype: 'b1b1 cgcg ee nn' },
  { name: 'Chocolate Slate', genotype: 'BB ee Dd' },
  { name: 'Chocolate Sweetgrass', genotype: 'b1b1 cgcg ee' },
  { name: 'Chocolate Tuxedo', genotype: 'BB cmcm ee' },
  { name: 'Cornish Palm', genotype: 'b1b1 Ccg' },
  { name: 'Dark Blue', genotype: 'bb cgcg Dd nn' },
  { name: 'Dark Gray', genotype: 'bb cgcg nn' },
  { name: 'Dilute Rusty Black', genotype: 'Bb nn Rr' },
  { name: 'Dilute Rusty Slate', genotype: 'Bb Dd nn Rr' },
  { name: 'Fall Fire', genotype: 'b1b1 cgcg Rr' },
  { name: 'Fawn', genotype: 'bb cmc'},
  { name: 'Frosted Dark Blue', genotype: 'bb cgcg Dd nn Rr'},
  { name: 'Frosted Dark Gray', genotype: 'bb cgcg nn Rr' },
  { name: 'Frosted Oregon Blue', genotype: 'bb cgc Dd nn Rr'},
  { name: 'Frosted Oregon Gray', genotype: 'bb cgc nn Rr' },
  { name: 'Golden Narragansett', genotype: 'bb nn Rr' },
  { name: 'Golden Phoenix', genotype: 'b1b1 Ccg nn Rr' },
  { name: 'Grizzled Black Painted', genotype: 'BB cmc' },
  { name: 'Grizzled Chocolate Painted', genotype: 'BB cmc ee' },
  { name: 'Grizzled Slate Painted', genotype: 'BB cmc Dd' },
  { name: 'Grizzled Lavender Painted', genotype: 'BB cmc DD' },
  { name: 'Grizzled Recessive Blue Painted', genotype: 'BB cmc slsl' },
  { name: 'Grizzled Rusty Painted', genotype: 'BB cmc Rr'},
  { name: 'Harvest Gold', genotype: 'b1b1 Rr' },
  { name: 'Jersey Buff', genotype: 'BB rr' },
  { name: 'Lavender', genotype: 'BB DD' },
  { name: 'Lavender Edged Bourbon Red', genotype: 'bb DD rr' },
  { name: 'Lavender Fall Fire', genotype: 'b1b1 cgcg DD Rr' },
  { name: 'Lavender Painted (Split Black Winged Bronze)', genotype: 'Bb1 cmc DD'},
  { name: 'Lavender Painted (Split Bronze)', genotype: 'Bb cmc DD'},
  { name: 'Lavender Palm', genotype: 'b1b1 cgcg DD nn' },
  { name: 'Lavender Red Bronze', genotype: 'bb DD Rr' },
  { name: 'Lavender Sweetgrass', genotype: 'b1b1 cgcg DD' },
  { name: 'Lavender Tuxedo', genotype: 'BB cmcm DD'},
  { name: 'Light Buff', genotype: 'b1b1 Ccg nn rr' },
  { name: 'Light Red', genotype: 'b1b1 Ccg rr' },
  { name: 'Lilac', genotype: 'bb DD' },
  { name: 'Marbled Black', genotype: 'BB cgcg nn' },
  { name: 'Marbled Lavender', genotype: 'BB cgcg DD nn' },
  { name: 'Marbled Slate', genotype: 'BB cgcg Dd nn' },
  { name: 'Mottled Auburn', genotype: 'bb cmcm ee' },
  { name: 'Mottled Black', genotype: 'Bb1 cgcg nn' },
  { name: 'Mottled Black Tuxedo', genotype: 'Bb1 cmcm' },
  { name: 'Mottled Black Winged Bronze', genotype: 'b1b1 cmcm' },
  { name: 'Mottled Bronze', genotype: 'bb cmcm' },
  { name: 'Mottled Brown Winged Auburn', genotype: 'b1b1 cmcm ee' },
  { name: 'Mottled Chocolate', genotype: 'Bb1 cgcg ee nn' },
  { name: 'Mottled Chocolate Dapple', genotype: 'Bb1 cgc ee nn' },
  { name: 'Mottled Dilute Rusty Brown', genotype: 'Bb1 cgcg ee nn Rr' },
  { name: 'Mottled Lavender', genotype: 'Bb1 cgcg DD nn' },
  { name: 'Mottled Recessive Blue Tuxedo', genotype: 'Bb1 cmcm slsl'},
  { name: 'Mottled Recessive Slate', genotype: 'bb cmcm slsl' },
  { name: 'Mottled Red', genotype: 'bb cmcm rr' },
  { name: 'Mottled Red Bronze', genotype: 'bb cmcm Rr' },
  { name: 'Mottled Rusty Black', genotype: 'Bb1 cgcg Rr' },
  { name: 'Mottled Rusty Slate', genotype: 'Bb1 cgcg Dd Rr' },
  { name: 'Mottled Silver Dapple', genotype: 'Bb1 cgc nn' },
  { name: 'Mottled Slate', genotype: 'Bb1 cgcg Dd nn' },
  { name: 'Narragansett', genotype: 'bb nn' },
  { name: 'Nebraskan', genotype: 'bb spsp'},
  { name: 'Oregon Blue', genotype: 'bb cgc Dd nn' },
  { name: 'Oregon Brown', genotype: 'bb cgc ee nn' },
  { name: 'Oregon Gray', genotype: 'bb cgc nn' },
  { name: 'Oregon Lavender Blue', genotype: 'bb cgc DD nn'},
  { name: 'Painted (Split Black Winged Bronze)', genotype: 'Bb1 cmc'},
  { name: 'Painted (Split Bronze)', genotype: 'Bb cmc'},
  { name: 'Pencilled Black Winged Bronze', genotype: 'b1b1 pnpn' },
  { name: 'Pencilled Blue Fall Fire', genotype: 'b1b1 cgcg Dd pnpn Rr' },
  { name: 'Pencilled Blue Palm', genotype: 'b1b1 cgcg Dd nn pnpn' },
  { name: 'Pencilled Blue Sweetgrass', genotype: 'b1b1 cgcg Dd pnpn' },
  { name: 'Pencilled Chocolate Palm', genotype: 'b1b1 cgcg ee nn pnpn' },
  { name: 'Pencilled Fall Fire', genotype: 'b1b1 cgcg pnpn Rr' },
  { name: 'Pencilled Lavender Fall Fire', genotype: 'b1b1 cgcg DD Rr' },
  { name: 'Pencilled Lavender Sweetgrass', genotype: 'b1b1 cgcg DD pnpn' },
  { name: 'Pencilled Light Red', genotype: 'b1b1 Ccg pnpn rr' },
  { name: 'Pencilled Palm', genotype: 'b1b1 cgcg nn pnpn' },
  { name: 'Pencilled Red Palm', genotype: 'b1b1 cgcg nn pnpn rr' },
  { name: 'Pencilled Sweetgrass', genotype: 'b1b1 cgcg pnpn' },
  { name: 'Recessive Blue Fawn', genotype: 'bb cmc slsl' },
  { name: 'Recessive Blue Narragansett', genotype: 'bb nn slsl' },
  { name: 'Recessive Blue Painted (Split Black Winged Bronze)', genotype: 'Bb1 cmc slsl'},
  { name: 'Recessive Blue Painted (Split Bronze)', genotype: 'Bb cmc slsl'},
  { name: 'Recessive Blue Sweetgrass', genotype: 'b1b1 cgcg slsl' },
  { name: 'Recessive Blue Tuxedo', genotype: 'BB cmcm slsl' },
  { name: 'Recessive Lilac', genotype: 'bb rr slsl' },
  { name: 'Recessive Slate', genotype: 'bb slsl' },
  { name: 'Red Bronze', genotype: 'bb Rr' },
  { name: 'Red Lilac', genotype: 'BB rr slsl'},
  { name: 'Red Recessive Slate', genotype: 'bb Rr slsl'},
  { name: 'Red Palm', genotype: 'b1b1 cgcg nn rr' },
  { name: 'Red Phoenix', genotype: 'b1b1 Ccg Rr' },
  { name: 'Red Slate', genotype: 'bb Dd' },
  { name: 'Red Sweetgrass', genotype: 'b1b1 cgcg rr' },
  { name: 'Red Tuxedo', genotype: 'BB cmcm rr' },
  { name: 'Regal Red', genotype: 'b1b1 rr' },
  { name: 'Royal Palm', genotype: 'b1b1 cgcg nn' },
  { name: 'Rusty Black', genotype: 'Bb Rr' },
  { name: 'Rusty Brown', genotype: 'Bb ee Rr' },
  { name: 'Rusty Slate', genotype: 'Bb Dd Rr' },
  { name: 'Rusty Painted (Split Black Winged Bronze)', genotype: 'Bb1 cmc Rr'},
  { name: 'Rusty Painted (Split Bronze)', genotype: 'Bb cmc Rr'},
  { name: 'Rusty Tuxedo', genotype: 'Bb cmcm Rr' },
  { name: 'Self Buff', genotype: 'b1b1 ee nn rr' },
  { name: 'Silver Auburn', genotype: 'bb ee nn' },
  { name: 'Silver Dapple', genotype: 'Bb cgc nn' },
  { name: 'Silver Palm', genotype: 'b1b1 cgc nn'},
  { name: 'Silver Tipped Black', genotype: 'BB nn' },
  { name: 'Silver Tipped Slate', genotype: 'BB Dd nn' },
  { name: 'Slate', genotype: 'BB Dd' },
  { name: 'Slate Painted (Split Black Winged Bronze)', genotype: 'Bb1 cmc Dd'},
  { name: 'Slate Painted (Split Bronze)', genotype: 'Bb cmc Dd'},
  { name: 'Slate Tuxedo', genotype: 'BB cmcm Dd' },
  { name: 'Sweetgrass', genotype: ' b1b1 cgcg' },
  { name: 'Tiger Bronze', genotype: 'b1b1 Ccg pnpn' },
  { name: 'Tiger Blue', genotype: 'b1b1 Ccg Dd pnpn' },
  { name: 'Tiger Lavender Blue', genotype: 'b1b1 Ccg DD pnpn' },
  { name: 'Tri-color Mottled Black', genotype: 'Bb1 cgcg' },
  { name: 'Tri-color Mottled Slate', genotype: 'Bb1 cgcg Dd' },
  { name: 'Tri-color Pencilled Blue Palm', genotype: 'b1b1 cgcg Dd nn pnpn Rr' },
  { name: 'Tri-color Pencilled Palm', genotype: 'b1b1 cgcg nn pnpn Rr' },
  { name: 'White', genotype: 'bb cc'},
  { name: 'White (Dark Brown Eyes)', genotype: 'bb cc' },
  { name: 'White (Blue Eyes)', genotype: 'BB cc' },
  { name: 'White (Light Brown Eyes)', genotype: 'b1b1 cc' },
  { name: 'White Winged Chocolate Fawn', genotype: 'b1b1 cmc ee'},
  { name: 'White Winged Fawn', genotype: 'b1b1 cmc'},
    
    
];








